<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        
        
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Mediatr" Version="12.4.1" />
    </ItemGroup>
</Project>
